applications/personas/urls.py
from django.urls import path
from .views import UsuarioCreateView, UsuarioListView, UsuarioDetailView, UsuarioUpdateView, UsuarioDeleteView, EmpleadoCreateView, EmpleadoListView, EmpleadoDetailView, EmpleadoUpdateView, EmpleadoDeleteView

app_name = 'personas_app'
urlpatterns = [
    path('usuarios/agregar/', UsuarioCreateView.as_view(), name='usuarios-agregar'),
    path('usuarios/', UsuarioListView.as_view(), name='usuarios-list'),
    path('usuarios/<int:pk>/', UsuarioDetailView.as_view(), name='usuarios-detail'),
    path('usuarios/<int:pk>/editar/', UsuarioUpdateView.as_view(), name='usuarios-edit'),
    path('usuarios/<int:pk>/eliminar/', UsuarioDeleteView.as_view(), name='usuarios-delete'),
    path('empleados/', EmpleadoListView.as_view(), name='empleados-list'),
    path('empleados/nuevo/', EmpleadoCreateView.as_view(), name='empleados-create'),
    path('empleados/<int:pk>/', EmpleadoDetailView.as_view(), name='empleados-detail'),
    path('empleados/<int:pk>/editar/', EmpleadoUpdateView.as_view(), name='empleados-edit'),
    path('empleados/<int:pk>/eliminar/', EmpleadoDeleteView.as_view(), name='empleados-delete'),
]

applications/vehiculos/urls.py
from django.urls import path
from .views import *

app_name = 'vehiculos_app'
urlpatterns = [
    path('vehiculos/', VehiculosDisponiblesView.as_view(), name='vehiculos-disponibles'),
    path('vehiculos/<int:pk>/', VehiculoDetailView.as_view(), name='vehiculo_detalle'),
    path('vehiculo/crear/', VehiculoCreateView.as_view(), name='vehiculo-create'),
    path('modelo/crear/', ModeloCreateView.as_view(), name='modelo-create'),
    path('proveedor/crear/', ProveedorCreateView.as_view(), name='proveedor-create'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria-create'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca-create'),
    path('ficha-tecnica/crear/', FichaTecnicaCreateView.as_view(), name='ficha-tecnica-create'),
    path('vehiculos/lista-admin/', VehiculosListAdminView.as_view(), name='vehiculo-list'),
    path('vehiculos/<int:pk>/eliminar/', VehiculoDeleteView.as_view(), name='vehiculo-delete'),
    
]

applications/ventas/urls.py
from django.urls import path
from .views import VentasListView, VentasDetailView, VentasCreateView, VentasUpdateView, VentasDeleteView

app_name = 'ventas'

urlpatterns = [
    path('ventas/', VentasListView.as_view(), name='ventas_list'),
    path('<int:pk>/', VentasDetailView.as_view(), name='ventas_detail'),
    path('ventanew/', VentasCreateView.as_view(), name='ventas_create'),
    path('<int:pk>/editar/', VentasUpdateView.as_view(), name='ventas_update'),
    path('<int:pk>/eliminar/', VentasDeleteView.as_view(), name='ventas_delete'),
]

concesionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.vehiculos.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.ventas.urls')),
    path('', include('applications.home.urls'))
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a>Adminitrar Proveedores</a></li>
        <li><a href="{% url 'vehiculos_app:vehiculo-list' %}">Administrar Vehiculos</a></li>
        <li><a href="{% url 'ventas:ventas_list' %}">Administrar Ventas</a></li>
        <li><a href="{% url 'personas_app:usuarios-list' %}">Administrar Usuarios</a></li>
        <li><a href="{% url 'personas_app:empleados-list' %}">Administrar Empleados</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar"></li>
        <li><a>Usuario</a></li>
      </ul>
    </div>
  </div>

templates/includes/pagination.html
<!--Paginacion-->
<div class="pagination-centered">
    <ul class="pagination" role="navigation" aria-label="Pagination">
        {% if page_obj.has_previous %}
            <li class="pagination-previous"><a href="?page=1">&laquo; Primera</a></li>
            <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
        {% else %}
            <li class="pagination-previous disabled">Primera</li>
            <li class="pagination-previous disabled">Anterior</li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="current"><span>{{ num }}</span></li>
            {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                <li><a href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
            <li class="pagination-next"><a href="?page={{ page_obj.paginator.num_pages }}">Ultima &raquo;</a></li>
        {% else %}
            <li class="pagination-next disabled">Siguiente</li>
            <li class="pagination-next disabled">Ultima</li>
        {% endif %}
    </ul>
</div>