applications/vehiculos/urls.py
from django.urls import path
from .views import *

app_name = 'vehiculos_app'
urlpatterns = [
    path('vehiculos/', VehiculosDisponiblesView.as_view(), name='vehiculos-disponibles'),
    path('vehiculos/<int:pk>/', VehiculoDetailView.as_view(), name='vehiculo_detalle'),
    path('vehiculo/crear/', VehiculoCreateView.as_view(), name='vehiculo-create'),
    path('modelo/crear/', ModeloCreateView.as_view(), name='modelo-create'),
    path('proveedor/crear/', ProveedorCreateView.as_view(), name='proveedor-create'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria-create'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca-create'),
    path('ficha-tecnica/crear/', FichaTecnicaCreateView.as_view(), name='ficha-tecnica-create'),
    path('vehiculos/lista-admin/', VehiculosListAdminView.as_view(), name='vehiculo-list'),
    path('vehiculos/<int:pk>/eliminar/', VehiculoDeleteView.as_view(), name='vehiculo-delete'),
    
]

concesionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.vehiculos.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.ventas.urls')),
    path('', include('applications.home.urls'))
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/pruebas/models.py
from django.db import models

# Create your models here.
# models.py
from django.db import models
from django.contrib.auth.models import User

class Marca(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class ModeloAuto(models.Model):
    nombre = models.CharField(max_length=100)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Vehiculo(models.Model):
    modelo = models.ForeignKey(ModeloAuto, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    año = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    color = models.CharField(max_length=50)
    km = models.IntegerField()
    motor = models.CharField(max_length=100)
    transmision = models.CharField(max_length=50)
    combustible = models.CharField(max_length=50)
    estado = models.CharField(max_length=50, choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')])

    def __str__(self):
        return f"{self.modelo} - {self.año}"

class FichaTecnica(models.Model):
    vehiculo = models.OneToOneField(Vehiculo, on_delete=models.CASCADE)
    detalles = models.TextField()

    def __str__(self):
        return f"Ficha Técnica - {self.vehiculo}"

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    dni = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Comentario(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentario de {self.cliente} sobre {self.vehiculo}"

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return self.nombre

class Compra(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    cantidad = models.IntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Compra de {self.cantidad} {self.vehiculo} de {self.proveedor}"

class Stock(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

    def __str__(self):
        return f"Stock de {self.vehiculo}"

class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Venta de {self.vehiculo} a {self.cliente}"

class Financiacion(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    monto_financiado = models.DecimalField(max_digits=10, decimal_places=2)
    cuotas = models.IntegerField()
    interes = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"Financiación de {self.cliente} para {self.vehiculo}"

class Trabajador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    puesto = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nombre} {self.apellido} - {self.puesto}"

applications/vehiculos/models.py
from django.db import models
from applications.inventario.models import Proveedor
from django.urls import reverse

# Create your models here.
class Categorias(models.Model):
    CATEGORIA_CHOICES = (
        ('0','chata'),
        ('1','auto'),
        ('2','moto'),
        ('3','cuatri'),
    )
    tipoVehiculo = models.CharField( max_length=1, choices=CATEGORIA_CHOICES)

    def __str__(self):
        return self.get_tipoVehiculo_display()

class Marcas(models.Model):
    marca = models.CharField( max_length=50)

    def __str__(self):
        return self.marca
class FichasTecnicas(models.Model):
    CANTIDAD_CHOICES = (
        ('0','2'),
        ('1','3'),
        ('2','4'),
        ('3','5'),
        
    )
    puertas = models.CharField( null=True, blank=True, max_length=1, choices=CANTIDAD_CHOICES)
    cilindradas = models.CharField(max_length=50)
    TIPO_CHOICES = (
        ('0','electricidad'),
        ('1','nafta'),
        ('2','diesel'),
        ('3','gas'),
    )
    combustible = models.CharField( null=True,max_length=1, choices=TIPO_CHOICES)
    paisFabrica = models.CharField( max_length=50)
    
    def __str__(self):
        return f"{self.cilindradas} - {self.get_combustible_display()}"


class Modelos(models.Model):
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    marcas = models.ForeignKey(Marcas, on_delete=models.CASCADE)
    modelo = models.CharField('Nombre del modelo', max_length=50)
    fichaTecnica = models.ForeignKey(FichasTecnicas, on_delete=models.CASCADE)
    año = models.DateField()
    #portada = models.ImageField(, upload_to=None, height_field=None, width_field=None, max_length=None)

    def __str__(self):
        return f"{self.modelo} ({self.año.strftime('%Y')})"


class Vehiculo(models.Model):
    modelos = models.ForeignKey(Modelos, on_delete=models.CASCADE)
    color = models.CharField(max_length=50)
    km = models.PositiveIntegerField()
    detalles = models.CharField(max_length=50, null=True, blank=True)
    #---------------------------------------------------
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    compra = models.PositiveIntegerField('precio compra',null=True)
    venta = models.PositiveIntegerField('precio venta')
    disponibilidad = models.BooleanField(null=True)
    portada = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=None, null=True)

    def __str__(self):
        return f"{self.modelos} - {self.color}"







    

applications/vehiculos/forms.py
from django import forms
from .models import Marcas, Categorias, Modelos,Vehiculo

class VehiculoSearchForm(forms.Form):
    query = forms.CharField(required=False, label='Buscar por modelo o marca')
    marca = forms.ModelChoiceField(queryset=Marcas.objects.all(), required=False, label='Marcas')
    categoria = forms.ModelChoiceField(queryset=Categorias.objects.all(), required=False, label='Categoría')
    km_min = forms.IntegerField(label='Km mínimo', required=False)
    km_max = forms.IntegerField(label='Km máximo', required=False)
    año_min = forms.IntegerField(label='Año mínimo', required=False)
    año_max = forms.IntegerField(label='Año máximo', required=False)
    precio_min = forms.IntegerField(label='Precio mínimo', required=False)
    precio_max = forms.IntegerField(label='Precio máximo', required=False)


class ModelosForm(forms.ModelForm):
    class Meta:
        model = Modelos
        fields = ['categoria', 'marcas', 'modelo', 'fichaTecnica', 'año']
        widgets = {
            'año': forms.DateInput(attrs={'type': 'date'}),
        }


class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['modelos', 'color', 'km', 'detalles', 'proveedor', 'compra', 'venta', 'disponibilidad']
        widgets = {
            'compra': forms.NumberInput(attrs={'type': 'number'}),
            'venta': forms.NumberInput(attrs={'type': 'number'}),
            'disponibilidad': forms.CheckboxInput(),
        }

applications/vehiculos/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Vehiculo, Modelos,Marcas, Categorias, FichasTecnicas
from applications.inventario.models import Proveedor
from .forms import VehiculoSearchForm, ModelosForm, VehiculoForm
from django.contrib.staticfiles.storage import staticfiles_storage
from django.utils.dateparse import parse_date

class VehiculosDisponiblesView(ListView):
    model = Vehiculo
    template_name = 'vehiculos/vehiculos_disponibles.html'
    context_object_name = 'vehiculos'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = VehiculoSearchForm(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            marca = form.cleaned_data['marca']
            categoria = form.cleaned_data['categoria']
            km_min = form.cleaned_data['km_min']
            km_max = form.cleaned_data['km_max']
            año_min = form.cleaned_data['año_min']
            año_max = form.cleaned_data['año_max']
            precio_min = form.cleaned_data['precio_min']
            precio_max = form.cleaned_data['precio_max']

            if query:
                queryset = queryset.filter(
                    modelos__nombre__icontains=query
                ) | queryset.filter(
                    modelos__marca__marca__icontains=query
                )

            if marca:
                queryset = queryset.filter(modelos__marcas=marca)
                
            if categoria:
                queryset = queryset.filter(modelos__categoria=categoria)
                
            if km_min is not None:
                queryset = queryset.filter(km__gte=km_min)
                
            if km_max is not None:
                queryset = queryset.filter(km__lte=km_max)
                
            if año_min is not None:
                queryset = queryset.filter(modelos__año__gte=año_min)
                
            if año_max is not None:
                queryset = queryset.filter(modelos__año__lte=año_max)
                
            if precio_min is not None:
                queryset = queryset.filter(venta__gte=precio_min)
                
            if precio_max is not None:
                queryset = queryset.filter(venta__lte=precio_max)

        return queryset

class VehiculosListAdminView(ListView):
    model = Vehiculo
    template_name = 'vehiculos/vehiculos_list_admin.html'
    context_object_name = 'vehiculos'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = VehiculoSearchForm(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            marca = form.cleaned_data['marca']
            categoria = form.cleaned_data['categoria']
            km_min = form.cleaned_data['km_min']
            km_max = form.cleaned_data['km_max']
            año_min = form.cleaned_data['año_min']
            año_max = form.cleaned_data['año_max']
            precio_min = form.cleaned_data['precio_min']
            precio_max = form.cleaned_data['precio_max']

            if query:
                queryset = queryset.filter(
                    modelos__modelo__icontains=query
                ) | queryset.filter(
                    modelos__marcas__marca__icontains=query
                )

            if marca:
                queryset = queryset.filter(modelos__marcas=marca)
                
            if categoria:
                queryset = queryset.filter(modelos__categoria=categoria)
                
            if km_min is not None:
                queryset = queryset.filter(km__gte=km_min)
                
            if km_max is not None:
                queryset = queryset.filter(km__lte=km_max)
                
            if año_min:
                try:
                    año_min_date = parse_date(f"{año_min}-01-01")  # Convierte el año a formato de fecha
                    queryset = queryset.filter(modelos__año__gte=año_min_date)
                except ValueError:
                    pass  # Ignora el valor si no es un año válido
                
            if año_max:
                try:
                    año_max_date = parse_date(f"{año_max}-12-31")  # Convierte el año a formato de fecha
                    queryset = queryset.filter(modelos__año__lte=año_max_date)
                except ValueError:
                    pass  # Ignora el valor si no es un año válido
                
            if precio_min is not None:
                queryset = queryset.filter(venta__gte=precio_min)
                
            if precio_max is not None:
                queryset = queryset.filter(venta__lte=precio_max)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = VehiculoSearchForm(self.request.GET)
        context['background_image'] = staticfiles_storage.url('images/auto.avif')
        return context



class VehiculoDetailView(DetailView):
    model = Vehiculo
    template_name = 'vehiculos/vehiculo_detalle.html'
    context_object_name = 'vehiculo'


class VehiculoCreateView(CreateView):
    model = Vehiculo
    form_class = VehiculoForm
    template_name = 'vehiculos/vehiculo_create.html'
    success_url = reverse_lazy('vehiculos_app:vehiculo-list')

class ModeloCreateView(CreateView):
    model = Modelos
    form_class = ModelosForm
    template_name = 'vehiculos/modelo_create.html'
    success_url = reverse_lazy('vehiculos_app:vehiculo-create')


class ProveedorCreateView(CreateView):
    model = Proveedor
    template_name = 'vehiculos/proveedor_create.html'
    fields = ['nombre', 'apellido', 'direccion', 'telefono', 'mail', 'paginaWeb', 'estado']
    success_url = reverse_lazy('vehiculos_app:vehiculo-create')

class CategoriaCreateView(CreateView):
    model = Categorias
    template_name = 'vehiculos/categoria_create.html'
    fields = ['tipoVehiculo']
    success_url = reverse_lazy('vehiculos_app:categoria-create')

class MarcaCreateView(CreateView):
    model = Marcas
    template_name = 'vehiculos/marca_create.html'
    fields = ['marca']
    success_url = reverse_lazy('vehiculos_app:marca-create')

class FichaTecnicaCreateView(CreateView):
    model = FichasTecnicas
    template_name = 'vehiculos/ficha_tecnica_create.html'
    fields = ['puertas', 'cilindradas', 'combustible', 'paisFabrica']
    success_url = reverse_lazy('vehiculos_app:ficha-tecnica-create')

class VehiculoDeleteView(DeleteView):
    model = Vehiculo
    template_name = 'vehiculos/vehiculo_confirm_delete.html'
    success_url = reverse_lazy('vehiculos_app:vehiculo-list')

templates/vehiculos/categoria_create.html
{% extends 'baseAdmin.html' %}
{% block title %} Crear Categoría {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Crear Categoría</h1>

      <form method="post">
        {% csrf_token %}
        
        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.tipoVehiculo.label_tag }}
            {{ form.tipoVehiculo }}
          </div>
        </div>

        <div class="text-center">
          <button type="submit" class="button primary">Guardar</button>
        </div>
      </form>

      <div class="text-center">
        <a href="{% url 'vehiculos_app:modelo-create' %}" class="button secondary">Volver a la creación de modelo</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/vehiculos/ficha_tecnica_create.html
{% extends 'baseAdmin.html' %}
{% block title %} Crear Ficha Técnica {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Crear Ficha Técnica</h1>

      <form method="post">
        {% csrf_token %}
        
        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.puertas.label_tag }}
            {{ form.puertas }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.cilindradas.label_tag }}
            {{ form.cilindradas }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.combustible.label_tag }}
            {{ form.combustible }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.paisFabrica.label_tag }}
            {{ form.paisFabrica }}
          </div>
        </div>

        <div class="text-center">
          <button type="submit" class="button primary">Guardar</button>
        </div>
      </form>

      <div class="text-center">
        <a href="{% url 'vehiculos_app:modelo-create' %}" class="button secondary">Volver a la creación de modelo</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/vehiculos/vehiculo_create.html
{% extends 'baseAdmin.html' %}
{% block title %} Crear Vehículo {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Crear Vehículo</h1>

      <form method="post">
        {% csrf_token %}
        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            <label for="{{ form.modelos.id_for_label }}">Modelo</label>
            {{ form.modelos }}
          </div>
          <div class="cell shrink">
            <a href="{% url 'vehiculos_app:modelo-create' %}" class="button secondary small">Crear nuevo modelo</a>
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            <label for="{{ form.proveedor.id_for_label }}">Proveedor</label>
            {{ form.proveedor }}
          </div>
          <div class="cell shrink">
            <a href="{% url 'vehiculos_app:proveedor-create' %}" class="button secondary small">Crear nuevo proveedor</a>
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.color.label_tag }}
            {{ form.color }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.km.label_tag }}
            {{ form.km }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.detalles.label_tag }}
            {{ form.detalles }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.compra.label_tag }}
            {{ form.compra }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.venta.label_tag }}
            {{ form.venta }}
          </div>
        </div>

        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.disponibilidad.label_tag }}
            {{ form.disponibilidad }}
          </div>
        </div>

        <div class="text-center">
          <button type="submit" class="button primary">Guardar</button>
        </div>
      </form>

      <div class="text-center">
        <a href="{% url 'vehiculos_app:vehiculo-list' %}" class="button secondary">Volver a la lista</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/vehiculos/vehiculos_disponibles.html
{% extends 'base.html' %}


{% block content %}

{% load static %}
<div class="hero-wrap js-fullheight" style="background-image: url('{{ background_image }}');">
        <div class="overlay"></div>
        <div class="container"> 
            <div class="row no-gutters slider-text js-fullheight align-items-center" data-scrollax-parent="true">
                <div class="col-md-7 ftco-animate">
                    <span class="subheading" style="color: rgb(252, 251, 251);">Bienvenido a Dream Cars</span>
                    <h1 style="color: rgb(252, 251, 251);">Haz realidad tu sueño sobre ruedas</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="grid-container">
        <div class="grid-x grid-margin-x">
            <div class="cell small-12 medium-3 large-3">
                <form method="get">
                    <div class="form-group">
                        <label for="id_query">Buscar por modelo o marca:</label>
                        {{ form.query }}
                    </div>
                    <div class="form-group">
                        <label>Marcas:</label>
                        {{ form.marca }}
                    </div>
                    <div class="form-group">
                        <label>Categoría:</label>
                        {{ form.categoria }}
                    </div>
                    <div class="form-group">
                        <label for="id_km_min">Km mínimo:</label>
                        {{ form.km_min }}
                        <label for="id_km_max">Km máximo:</label>
                        {{ form.km_max }}
                    </div>
                    <div class="form-group">
                        <label for="id_año_min">Año mínimo:</label>
                        {{ form.año_min }}
                        <label for="id_año_max">Año máximo:</label>
                        {{ form.año_max }}
                    </div>
                    <div class="form-group">
                        <label for="id_precio_min">Precio mínimo:</label>
                        {{ form.precio_min }}
                        <label for="id_precio_max">Precio máximo:</label>
                        {{ form.precio_max }}
                    </div>
                    <button type="submit" class="button primary">Buscar</button>
                </form>
            </div>
    
            <div class="cell small-12 medium-9 large-9">
                <h1>Vehículos Disponibles</h1>
                <ul>
                    {% for vehiculo in vehiculos %}
                        <li>{{ vehiculo }}</li>
                    {% endfor %}
                </ul>
                
                <div>
                    {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            {% if vehiculos.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page=1">&laquo; Primero</a>
                            </li>
                            <li class="pagination-previous">
                                <a href="?page={{ vehiculos.previous_page_number }}">Anterior</a>
                            </li>
                            {% endif %}
                            
                            {% for page_num in vehiculos.paginator.page_range %}
                                {% if page_num == vehiculos.number %}
                                <li class="current"><span class="show-for-sr">Estás en la página</span> {{ page_num }}</li>
                                {% else %}
                                <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                {% endif %}
                            {% endfor %}
                            
                            {% if vehiculos.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{ vehiculos.next_page_number }}">Siguiente</a>
                            </li>
                            <li class="pagination-next">
                                <a href="?page={{ vehiculos.paginator.num_pages }}">Último &raquo;</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/vehiculos/vehiculos_list_admin.html
{% extends 'baseAdmin.html' %}

{% block title %}Lista de Vehículos{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <h1 class="text-center">Lista de Vehículos</h1>

    <!-- Formulario de búsqueda y botón para crear -->
    <form method="get" class="grid-x grid-margin-x grid-padding-x align-middle">
        <div class="cell small-12 medium-6 large-4">
            <label>Buscar por modelo o marca:
                <input type="text" name="query" value="{{ request.GET.query }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Marcas:
                <select name="marca">
                    <option value="">----------</option>
                    {% for marca in form.fields.marca.queryset %}
                        <option value="{{ marca.pk }}" {% if marca.pk|stringformat:"s" == request.GET.marca %}selected{% endif %}>
                            {{ marca }}
                        </option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Categoría:
                <select name="categoria">
                    <option value="">----------</option>
                    {% for categoria in form.fields.categoria.queryset %}
                        <option value="{{ categoria.pk }}" {% if categoria.pk|stringformat:"s" == request.GET.categoria %}selected{% endif %}>
                            {{ categoria }}
                        </option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <!-- Otros filtros aquí -->
        <div class="cell small-12 medium-6 large-4">
            <label>Km mínimo:
                <input type="number" name="km_min" value="{{ request.GET.km_min }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Km máximo:
                <input type="number" name="km_max" value="{{ request.GET.km_max }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Año mínimo:
                <input type="number" name="año_min" value="{{ request.GET.año_min }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Año máximo:
                <input type="number" name="año_max" value="{{ request.GET.año_max }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Precio mínimo:
                <input type="number" name="precio_min" value="{{ request.GET.precio_min }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <label>Precio máximo:
                <input type="number" name="precio_max" value="{{ request.GET.precio_max }}">
            </label>
        </div>
        <div class="cell small-12 medium-6 large-4">
            <button type="submit" class="button">Buscar</button>
        </div>
        <div class="cell small-12 medium-6 large-4 text-right">
            <a href="{% url 'vehiculos_app:vehiculo-create' %}" class="button success">Crear Vehículo</a>
        </div>
    </form>

    <!-- Lista de Vehículos -->
    <ul class="no-bullet grid-x grid-margin-x grid-margin-y small-up-1 medium-up-2">
        {% for vehiculo in vehiculos %}
        <li class="cell">
            <div class="card">
                <div class="card-section">
                    <div class="grid-x grid-margin-x align-middle">
                        <div class="cell auto">
                            <a href="{% url 'vehiculos_app:vehiculo_detalle' vehiculo.pk %}">
                                {{ vehiculo.modelos }} - {{ vehiculo.color }}
                            </a>
                        </div>
                        <div class="cell shrink">
                            <form method="post" action="{% url 'vehiculos_app:vehiculo-delete' vehiculo.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="button alert small">Eliminar</button>
                            </form>
                        </div>
                    </div>
                    <p><strong>Precio:</strong> {{ vehiculo.venta }}$</p>
                    <p><strong>Kilómetros:</strong> {{ vehiculo.km }}</p>
                    <p><strong>Año:</strong> {{ vehiculo.modelos.año.year }}</p>
                    <p><strong>Disponibilidad:</strong> {{ vehiculo.disponibilidad|yesno:"Sí,No" }}</p>
                </div>
            </div>
        </li>
        {% endfor %}
        
    </ul>

    {% include 'includes/pagination.html' %}
</div>
{% endblock content %}