applications/personas/urls.py
from django.urls import path
from .views import UsuarioCreateView, UsuarioListView, UsuarioDetailView, UsuarioUpdateView, UsuarioDeleteView, EmpleadoCreateView, EmpleadoListView, EmpleadoDetailView, EmpleadoUpdateView, EmpleadoDeleteView

app_name = 'personas_app'
urlpatterns = [
    path('usuarios/agregar/', UsuarioCreateView.as_view(), name='usuarios-agregar'),
    path('usuarios/', UsuarioListView.as_view(), name='usuarios-list'),
    path('usuarios/<int:pk>/', UsuarioDetailView.as_view(), name='usuarios-detail'),
    path('usuarios/<int:pk>/editar/', UsuarioUpdateView.as_view(), name='usuarios-edit'),
    path('usuarios/<int:pk>/eliminar/', UsuarioDeleteView.as_view(), name='usuarios-delete'),
    path('empleados/', EmpleadoListView.as_view(), name='empleados-list'),
    path('empleados/nuevo/', EmpleadoCreateView.as_view(), name='empleados-create'),
    path('empleados/<int:pk>/', EmpleadoDetailView.as_view(), name='empleados-detail'),
    path('empleados/<int:pk>/editar/', EmpleadoUpdateView.as_view(), name='empleados-edit'),
    path('empleados/<int:pk>/eliminar/', EmpleadoDeleteView.as_view(), name='empleados-delete'),
]

concesionaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.vehiculos.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.ventas.urls')),
    path('', include('applications.home.urls'))
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/personas/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Usuarios(models.Model): #puede ser tanto cliente como usuario 
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.CharField(max_length=50)
    telefono = models.CharField(max_length=30)
    dni = models.CharField(max_length=12)
    mail = models.EmailField(max_length=70, null= True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

    def get_absolute_url(self):
        return reverse('usuarios-detail', args=[str(self.id)])


class Empleados(models.Model):
    PUESTO_CHOICES = (
        ('0','VENDEDOR'),
        ('1','ADMINISTRADOR'),
        ('2','USUARIO'),
        ('3','GERENTE'),
    )
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.CharField(max_length=50)
    telefono = models.CharField(max_length=30)
    dni = models.CharField(max_length=12)
    puesto = models.CharField( max_length=1, choices=PUESTO_CHOICES)
    mutual = models.CharField(max_length=50)
    edad = models.PositiveIntegerField()


    def __str__(self):
        return f"{self.nombre} {self.apellido} - {self.get_puesto_display()}"

applications/pruebas/models.py
from django.db import models

# Create your models here.
# models.py
from django.db import models
from django.contrib.auth.models import User

class Marca(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class ModeloAuto(models.Model):
    nombre = models.CharField(max_length=100)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Vehiculo(models.Model):
    modelo = models.ForeignKey(ModeloAuto, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    año = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    color = models.CharField(max_length=50)
    km = models.IntegerField()
    motor = models.CharField(max_length=100)
    transmision = models.CharField(max_length=50)
    combustible = models.CharField(max_length=50)
    estado = models.CharField(max_length=50, choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')])

    def __str__(self):
        return f"{self.modelo} - {self.año}"

class FichaTecnica(models.Model):
    vehiculo = models.OneToOneField(Vehiculo, on_delete=models.CASCADE)
    detalles = models.TextField()

    def __str__(self):
        return f"Ficha Técnica - {self.vehiculo}"

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    dni = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Comentario(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentario de {self.cliente} sobre {self.vehiculo}"

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return self.nombre

class Compra(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    cantidad = models.IntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Compra de {self.cantidad} {self.vehiculo} de {self.proveedor}"

class Stock(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

    def __str__(self):
        return f"Stock de {self.vehiculo}"

class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Venta de {self.vehiculo} a {self.cliente}"

class Financiacion(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    monto_financiado = models.DecimalField(max_digits=10, decimal_places=2)
    cuotas = models.IntegerField()
    interes = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"Financiación de {self.cliente} para {self.vehiculo}"

class Trabajador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=255)
    puesto = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nombre} {self.apellido} - {self.puesto}"

applications/personas/forms.py
from django import forms
from .models import Usuarios,Empleados

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = ['nombre', 'apellido', 'direccion', 'telefono', 'dni', 'mail']

class UsuarioSearchForm(forms.Form):
    query = forms.CharField(label='Buscar', max_length=100, required=False)


class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleados
        fields = '__all__'

class EmpleadosSearchForm(forms.Form):
    query = forms.CharField(label='Buscar', max_length=100, required=False)

applications/personas/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.db.models import Q  
from .models import Usuarios, Empleados
from .forms import UsuarioForm, UsuarioSearchForm, EmpleadosSearchForm, EmpleadoForm

class UsuarioCreateView(CreateView):
    model = Usuarios
    form_class = UsuarioForm
    template_name = 'personas/usuario_form.html'
    success_url = reverse_lazy('personas_app:usuarios-list')

class UsuarioListView(ListView):
    model = Usuarios
    template_name = 'usuarios/usuario_list.html'
    context_object_name = 'usuarios'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = UsuarioSearchForm(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            if query:
                queryset = queryset.filter(
                    Q(nombre__icontains=query) |
                    Q(apellido__icontains=query) |
                    Q(dni__icontains=query)
                )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UsuarioSearchForm(self.request.GET)
        return context

class UsuarioDetailView(DetailView):
    model = Usuarios
    template_name = 'personas/usuario_detail.html'
    context_object_name = 'usuario'

class UsuarioUpdateView(UpdateView):
    model = Usuarios
    form_class = UsuarioForm
    template_name = 'personas/usuario_form.html'
    context_object_name = 'usuario'
    success_url = reverse_lazy('personas_app:usuarios-list')

class UsuarioDeleteView(DeleteView):
    model = Usuarios
    template_name = 'personas/usuario_confirm_delete.html'
    context_object_name = 'usuario'
    success_url = reverse_lazy('personas_app:usuarios-list')

#----------------------------------------Views Empleados--------------------------------------------------
# views.py

class EmpleadoCreateView(CreateView):
    model = Empleados
    form_class = EmpleadoForm
    template_name = 'personas/empleado_form.html'
    success_url = reverse_lazy('personas_app:empleados-list')

class EmpleadoListView(ListView):
    model = Empleados
    template_name = 'personas/empleado_list.html'
    context_object_name = 'empleados'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        form = EmpleadosSearchForm(self.request.GET)  # Asumiendo que tienes un formulario de búsqueda similar
        if form.is_valid():
            query = form.cleaned_data['query']
            if query:
                queryset = queryset.filter(
                    Q(nombre__icontains=query) |
                    Q(apellido__icontains=query) |
                    Q(dni__icontains=query)
                )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = EmpleadosSearchForm(self.request.GET)  # Asumiendo que tienes un formulario de búsqueda similar
        return context

class EmpleadoDetailView(DetailView):
    model = Empleados
    template_name = 'personas/empleado_detail.html'
    context_object_name = 'empleado'

class EmpleadoUpdateView(UpdateView):
    model = Empleados
    form_class = EmpleadoForm
    template_name = 'personas/empleado_form.html'
    context_object_name = 'empleado'
    success_url = reverse_lazy('personas_app:empleados-list')

class EmpleadoDeleteView(DeleteView):
    model = Empleados
    template_name = 'personas/empleado_confirm_delete.html'
    context_object_name = 'empleado'
    success_url = reverse_lazy('personas_app:empleados-list')

templates/personas/empleado_confirm_delete.html
{% extends 'baseAdmin.html' %}
{% block title %} Confirmar Eliminación {% endblock title %}
{% block content %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Confirmar Eliminación</h1>
      <div class="callout alert">
        <p>¿Estás seguro de que deseas eliminar "{{ empleado.nombre }} {{ empleado.apellido }}"?</p>
        <form method="post">
          {% csrf_token %}
          <div class="button-group">
            <button type="submit" class="button alert">Eliminar</button>
            <a href="{% url 'personas_app:empleados-list' %}" class="button secondary">Cancelar</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/personas/empleado_detail.html
{% extends 'baseAdmin.html' %}
{% block title %} Detalles del Empleado {% endblock title %}
{% block content %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Detalles del Empleado</h1>
      
      <div class="callout">
        <p><strong>Nombre:</strong> {{ empleado.nombre }}</p>
        <p><strong>Dirección:</strong> {{ empleado.direccion }}</p>
        <p><strong>Teléfono:</strong> {{ empleado.telefono }}</p>
        <p><strong>DNI:</strong> {{ empleado.dni }}</p>
        <p><strong>Puesto:</strong> {{ empleado.get_puesto_display }}</p>
        <p><strong>Mutual:</strong> {{ empleado.mutual }}</p>
        <p><strong>Edad:</strong> {{ empleado.edad }}</p>
        <p><strong>Apellido:</strong> {{ empleado.apellido }}</p>
      </div>

      <div class="text-center">
        <a href="{% url 'personas_app:empleados-edit' empleado.pk %}" class="button primary">Editar</a>
        <a href="{% url 'personas_app:empleados-list' %}" class="button secondary">Volver a la lista</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/personas/empleado_form.html
{% extends 'baseAdmin.html' %}
{% block title %} Crear Empleado {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-padding-x align-center">
        <div class="cell small-10 medium-6 large-4">
            <h1 class="text-center">{% if form.instance.pk %}Editar{% else %}Agregar{% endif %} Empleado</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <button type="submit" class="button primary">Guardar</button>
                </div>
            </form>
            <div class="text-center">
                <a href="{% url 'personas_app:empleados-list' %}" class="button secondary">Volver a la lista</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/personas/empleado_list.html
{% extends 'baseAdmin.html' %}
{% block title %} Lista de Empleados {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Lista de Empleados</h1>

      <!-- Botón para crear un nuevo Empleado -->
      <div class="text-center">
        <a href="{% url 'personas_app:empleados-create' %}" class="button primary">Crear Empleado</a>
      </div>

      <!-- Formulario de búsqueda -->
      <form method="get">
        <label for="id_query" class="middle">Buscar Empleado:</label>
        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.query }}
          </div>
          <div class="cell shrink">
            <button type="submit" class="button primary">Buscar</button>
          </div>
        </div>
      </form>

      <!-- Lista de Empleado -->
      <ul class="no-bullet">
        {% for empleado in empleados %}
          <li class="card">
            <div class="card-section">
              <div class="grid-x grid-margin-x align-middle">
                <div class="cell auto">
                    <a href="{% url 'personas_app:empleados-detail' empleado.pk %}">
                        {{ empleado.nombre }} {{ empleado.apellido }}
                </div>
                <div class="cell shrink">
                  <a href="{% url 'personas_app:empleados-delete' empleado.pk %}" class="button alert small">
                    <i class="fa fa-trash"></i> Eliminar
                  </a>
                </div>
              </div>
            </div>
          </li>
        {% empty %}
          <li>No se encontraron Empleados.</li>
        {% endfor %}
      </ul>
      {% include 'includes/pagination.html' %}
    </div>
  </div>
</div>

{% endblock content %}

templates/personas/usuario_confirm_delete.html
{% extends 'baseAdmin.html' %}
{% block title %} Confirmar Eliminación {% endblock title %}
{% block content %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Confirmar Eliminación</h1>
      <div class="callout alert">
        <p>¿Estás seguro de que deseas eliminar "{{ usuario.nombre }} {{ usuario.apellido }}"?</p>
        <form method="post">
          {% csrf_token %}
          <div class="button-group">
            <button type="submit" class="button alert">Eliminar</button>
            <a href="{% url 'personas_app:usuarios-list' %}" class="button secondary">Cancelar</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/personas/usuario_detail.html
{% extends 'baseAdmin.html' %}
{% block title %} Detalles del Usuario {% endblock title %}
{% block content %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Detalles del Usuario</h1>
      
      <div class="callout">
        <p><strong>Nombre:</strong> {{ usuario.nombre }}</p>
        <p><strong>Apellido:</strong> {{ usuario.apellido }}</p>
        <p><strong>DNI:</strong> {{ usuario.dni }}</p>
        <p><strong>Dirección:</strong> {{ usuario.direccion }}</p>
        <p><strong>Teléfono:</strong> {{ usuario.telefono }}</p>
        <p><strong>Email:</strong> {{ usuario.mail }}</p>
      </div>

      <div class="text-center">
        <a href="{% url 'personas_app:usuarios-edit' usuario.pk %}" class="button primary">Editar</a>
        <a href="{% url 'personas_app:usuarios-list' %}" class="button secondary">Volver a la lista</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/personas/usuario_form.html
{% extends 'baseAdmin.html' %}
{% block title %} Crear Usuario {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-padding-x align-center">
        <div class="cell small-10 medium-6 large-4">
            <h1 class="text-center">{% if form.instance.pk %}Editar{% else %}Agregar{% endif %} Usuario</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <button type="submit" class="button primary">Guardar</button>
                </div>
            </form>
            <div class="text-center">
                <a href="{% url 'personas_app:usuarios-list' %}" class="button secondary">Volver a la lista</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/personas/usuarios_list.html
{% extends 'baseAdmin.html' %}
{% block title %} Lista de Usuarios {% endblock title %}
{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell medium-8 large-6">
      <h1 class="text-center">Lista de Usuarios</h1>

      <!-- Botón para crear un nuevo usuario -->
      <div class="text-center">
        <a href="{% url 'personas_app:usuarios-agregar' %}" class="button primary">Crear Usuario</a>
      </div>

      <!-- Formulario de búsqueda -->
      <form method="get">
        <label for="id_query" class="middle">Buscar usuarios:</label>
        <div class="grid-x grid-margin-x">
          <div class="cell auto">
            {{ form.query }}
          </div>
          <div class="cell shrink">
            <button type="submit" class="button primary">Buscar</button>
          </div>
        </div>
      </form>

      <!-- Lista de usuarios -->
      <ul class="no-bullet">
        {% for usuario in usuarios %}
          <li class="card">
            <div class="card-section">
              <div class="grid-x grid-margin-x align-middle">
                <div class="cell auto">
                  <a href="{% url 'personas_app:usuarios-detail' usuario.pk %}">
                    {{ usuario.nombre }} {{ usuario.apellido }} - {{ usuario.dni }}
                  </a>
                </div>
                <div class="cell shrink">
                  <a href="{% url 'personas_app:usuarios-delete' usuario.pk %}" class="button alert small">
                    <i class="fa fa-trash"></i> Eliminar
                  </a>
                </div>
              </div>
            </div>
          </li>
        {% empty %}
          <li>No se encontraron usuarios.</li>
        {% endfor %}
      </ul>
      {% include 'includes/pagination.html' %}
    </div>
  </div>
</div>

{% endblock content %}